name: Dynamic matrix
on:
  workflow_dispatch:
    inputs:
      os:
        description: dynamic matrix preparation
        default: ubuntu-latest,windows-latest
        type: string
jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Github script
        id: split_step
        uses: actions/github-script@v7
        with:
          script: "return {os:'${{inputs.os}}'.split(',')}"
          result-encoding: json
      - name: prepare matrix
        run: |
          echo '${{steps.split_step.outputs.result}}'
      - name: printing env variables
        run: echo '${{toJson(env)}}'
    outputs:
      matrix-arrays: ${{steps.split_step.outputs.result}}
  use-matrix-input:
    runs-on: ${{matrix.os}}
    needs: [prepare-matrix]
    strategy:
      matrix:
        os: ${{fromJson(needs.prepare-matrix.outputs.matrix-arrays).os}}
    steps:
      - name: Print OS names
        run: echo '${{fromJson(needs.prepare-matrix.outputs.matrix-arrays)}}'
