name: Dynamic matrix
on:
  workflow_dispatch:
    inputs:
      os:
        description: dynamic matrix preparation
        default: ubuntu-latest,windows-latest
        type: string
jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Github script
        id: split_step
        uses: actions/github-script@v7
        with:
          script: return {os:'${{inputs.os}}'.split(",")}
      - name: prepare matrix
        run: |
          echo 'OS_OPTIONS=${{steps.split_step.outputs.result}}' >> $GITHUB_ENV
      - name: printing env variables
        run: echo '${{toJson(env)}}'
    outputs:
      matrix-arrays: ${{steps.split_step.outputs.result}}
  use-matrix-input:
    runs-on: ubuntu-latest
    needs: [prepare-matrix]
    steps:
      - name: Print OS names
        run: echo '${{toJson(needs.prepare-matrix.outputs.matrix-arrays).os}}'
