name: Dynamic matrix
on:
  workflow_dispatch:
    inputs:
      os:
        description: dynamic matrix preparation
        default: ubuntu-latest,windows-latest
        type: string
jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Github script
        id: split_step
        uses: actions/github-script@v7
        with:
          script: return '${{inputs.os}}'.split()
      - name: prepare matrix
        run: |
          echo '${{toJSON(steps)}}'
